[package]
name = "systools"
version = "0.1.0"
authors = ["Hans Grob <H.Grob@ifndef.de>"]
edition = "2018"

[dependencies]
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
chrono      = "0.4"
reqwest     = { version = "0.10", features = ["blocking"] }
